#!/bin/bash

# Script pour créer toute la structure de liquid-war-java dans liquid-war-upc
# avec des fichiers vides

SOURCE_DIR="/home/ajinou/Bureau/Projet CPOO/liquid-war-java"
TARGET_DIR="/home/ajinou/Bureau/Projet CPOO/liquid-war-upc"

echo "Création de la structure complète..."

# Créer tous les dossiers Java
echo "Création des dossiers Java..."
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/audio"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/config/factory"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/command"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/entities"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/factory"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/observer"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/network"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/ai"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/gradient"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/util"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/decorator"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/input"
mkdir -p "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu"

# Créer tous les dossiers de test
echo "Création des dossiers de test..."
mkdir -p "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/audio"
mkdir -p "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/config/factory"
mkdir -p "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/controller/command"
mkdir -p "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/model/entities"
mkdir -p "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/model/factory"
mkdir -p "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/model/observer"
mkdir -p "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/network"
mkdir -p "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service"
mkdir -p "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/util"

# Créer les dossiers resources
echo "Création des dossiers resources..."
mkdir -p "$TARGET_DIR/src/main/resources/images"
mkdir -p "$TARGET_DIR/src/main/resources/map-screens"
mkdir -p "$TARGET_DIR/src/main/resources/maps"
mkdir -p "$TARGET_DIR/src/main/resources/music"
mkdir -p "$TARGET_DIR/src/main/resources/sfx"

# Créer le dossier gradle
echo "Création du dossier gradle..."
mkdir -p "$TARGET_DIR/gradle/wrapper"

# Créer tous les fichiers Java (vides)
echo "Création des fichiers Java (vides)..."

# Main source files
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/audio/AudioManager.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/config/GameConfig.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/config/GameOptions.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/config/RenderConfig.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/config/factory/ConfigFactory.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/config/factory/GameConfiguration.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/DebugLauncher.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/LiquidWarGame.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/Main.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/MainWithMenu.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/MenuManager.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/NetworkLiquidWarGame.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/command/Command.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/command/CommandHistory.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/command/MoveCursorCommand.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/GameState.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/MapLoader.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/entities/Cursor.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/entities/Fighter.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/entities/Mesh.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/factory/EntityFactory.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/observer/GameEvent.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/observer/GameObserver.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/observer/GameSubject.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/network/NetworkClient.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/network/NetworkGameController.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/network/NetworkMessage.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/network/NetworkProtocol.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/network/NetworkServer.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/CombatEngine.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/GameInitializer.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/MovementEngine.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/OptimizedGradientEngine.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/OptimizedMovementEngine.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/ParallelMovementEngine.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/ParallelPathfindingEngine.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/PathfindingEngine.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/ai/AIStrategy.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/ai/AggressiveAI.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/ai/DefensiveAI.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/ai/RandomAI.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/gradient/BFSGradientStrategy.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/gradient/DijkstraGradientStrategy.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/gradient/GradientStrategy.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/util/DirectionTables.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/util/GameLogger.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/util/MeshBuilder.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/util/ObjectPool.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/util/PrecisionTimer.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/AIController.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/GameCanvas.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/GameCanvasConfiguration.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/GameInitializationManager.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/GamePanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/GameRenderer.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/GameStatsPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/GradientVisualizer.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/WaterDistortionEffect.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/decorator/AuraDecorator.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/decorator/CompositeDecorator.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/decorator/ParticleDecorator.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/decorator/TrailDecorator.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/input/GameInputHandler.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/input/PlayerCursorController.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/ClientConnectPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/GameModeMenuPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/HelpMenuPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/MainMenuPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/MapSelectionMenuPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/NetworkMenuPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/OptionsMenuPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/PauseMenuPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/ServerSetupPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/TeamConfigMenuPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/TimeModeMenuPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/TrioConfigMenuPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/VictoryPanel.java"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/WaitingRoomPanel.java"

# Créer tous les fichiers de test (vides)
echo "Création des fichiers de test (vides)..."
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/NetworkTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/PerformanceTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/audio/AudioManagerTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/config/ConfigFactoryTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/config/GameConfigTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/config/GameOptionsTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/config/RenderConfigTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/config/factory/GameConfigurationTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/controller/command/CommandHistoryTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/controller/command/MoveCursorCommandTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/model/GameStateTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/model/MapLoaderTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/model/entities/CursorTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/model/entities/FighterTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/model/entities/MeshTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/model/factory/EntityFactoryTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/model/observer/ObserverPatternTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/network/NetworkClientTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/network/NetworkGameControllerTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/network/NetworkServerTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service/AIStrategyTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service/CombatEngineTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service/GameInitializerTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service/GradientStrategyTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service/MovementEngineTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service/OptimizedGradientEngineTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service/OptimizedMovementEngineTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service/ParallelMovementEngineTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service/ParallelPathfindingEngineTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/service/PathfindingEngineTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/util/DirectionTablesTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/util/GameLoggerTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/util/MeshBuilderTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/util/ObjectPoolTest.java"
touch "$TARGET_DIR/src/test/java/fr/uparis/informatique/cpoo5/liquidwar/util/PrecisionTimerTest.java"

# Créer les fichiers de configuration
echo "Création des fichiers de configuration..."
touch "$TARGET_DIR/build.gradle"
touch "$TARGET_DIR/settings.gradle"
touch "$TARGET_DIR/gradle/wrapper/gradle-wrapper.properties"

# Créer les scripts shell
echo "Création des scripts shell..."
touch "$TARGET_DIR/gradlew"
touch "$TARGET_DIR/gradlew.bat"
touch "$TARGET_DIR/run.sh"
touch "$TARGET_DIR/add_packages.sh"
touch "$TARGET_DIR/debug_run.sh"
touch "$TARGET_DIR/install-icon.sh"
touch "$TARGET_DIR/test_network.sh"
touch "$TARGET_DIR/update-desktop.sh"

# Créer le fichier desktop
touch "$TARGET_DIR/Liquid War.desktop"

# Créer les fichiers README.md (vides)
echo "Création des fichiers README.md (vides)..."
touch "$TARGET_DIR/src/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/audio/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/config/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/config/factory/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/controller/command/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/entities/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/model/observer/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/network/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/ai/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/service/gradient/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/util/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/decorator/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/input/README.md"
touch "$TARGET_DIR/src/main/java/fr/uparis/informatique/cpoo5/liquidwar/view/menu/README.md"
touch "$TARGET_DIR/src/main/resources/maps/README.md"

# Créer les fichiers de ressources (vides - l'utilisateur les remplira)
echo "Création des fichiers de ressources (vides)..."
touch "$TARGET_DIR/src/main/resources/images/Logo-Liquid-War.png"
touch "$TARGET_DIR/src/main/resources/map-screens/2d.png"
touch "$TARGET_DIR/src/main/resources/map-screens/bubbles.png"
touch "$TARGET_DIR/src/main/resources/map-screens/puckman.png"
touch "$TARGET_DIR/src/main/resources/map-screens/tiles.png"
touch "$TARGET_DIR/src/main/resources/map-screens/village.png"
touch "$TARGET_DIR/src/main/resources/maps/2d.bmp"
touch "$TARGET_DIR/src/main/resources/maps/2d.txt"
touch "$TARGET_DIR/src/main/resources/maps/bubbles.bmp"
touch "$TARGET_DIR/src/main/resources/maps/bubbles.txt"
touch "$TARGET_DIR/src/main/resources/maps/puckman.bmp"
touch "$TARGET_DIR/src/main/resources/maps/puckman.txt"
touch "$TARGET_DIR/src/main/resources/maps/tag.bmp"
touch "$TARGET_DIR/src/main/resources/maps/tag.txt"
touch "$TARGET_DIR/src/main/resources/maps/tiles.bmp"
touch "$TARGET_DIR/src/main/resources/maps/tiles.txt"
touch "$TARGET_DIR/src/main/resources/maps/village.bmp"
touch "$TARGET_DIR/src/main/resources/maps/village.txt"
touch "$TARGET_DIR/src/main/resources/music/fodder.mid"
touch "$TARGET_DIR/src/main/resources/sfx/splash1.wav"
touch "$TARGET_DIR/src/main/resources/sfx/water.wav"

echo "✅ Structure créée avec succès !"
echo "Tous les fichiers sont vides et prêts à être remplis."

